name: Android CI

on:
  workflow_dispatch:         
  push:
    branches:
      - '**'
  #pull_request:
   # branches: [ feature/GitHub_Actions ]
  
  #Set your workflow to run every day of the week at 20:00 UTC(1:30 AM)
  schedule:
  - cron:  0 21 * * 0-6

jobs:
  Build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 0
        clean: true
        submodules: true
        lfs: true
  
    - name: Build & Test with Gradle
      shell: bash
      run: |
           echo 'Running'
           ./gradlew --refresh-dependencies --full-stacktrace clean assembleRelease 
    
   # - name: Upload APK
    #  uses: actions/upload-artifact@v2.2.0
     # with:
      #  name: APK's for ReferenceApp & PIMDemoApp
       # path: |
        #  ${{github.workspace}}/Source/rap/Source/AppFramework/appFramework/build/outputs/apk/release/*.apk
         # ${{github.workspace}}/source/pim/Source/DemoApp/app/build/outputs/apk/release/*.apk
    
    #publish to artifactory only for master,develop and release/platform_*
    - name: Publish To Artifactory
      if: contains(github.ref,'master') || contains(github.ref,'develop') || contains(github.ref,'release/platform_')        
      shell: bash
      run: |
           ./gradlew --full-stacktrace saveResDep saveAllResolvedDependenciesGradleFormat artifactoryPublish
  
    #- name: Jacoco Reports
     # shell: bash
      #run: |
       #    ./gradlew test
        #   ./gradlew jacocoTestReport
    
    - name: Lint
      shell: bash
      run: |
           ./gradlew  \
            :csw:lint
